import { Inter } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import SidebarMobile from "@/components/SidebarMobile";
import "./globals.css";
import Backdrop from "@/components/Backdrop";
import Coins from "@/components/Coins";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-full">
          <Sidebar />
          <SidebarMobile />
          <Backdrop />
          <Coins />
          <main className="sm:pl-56 pb-24 md:pl-56 md:pb-0 flex bg-black box-border w-full">
            <div className="w-full h-full z-20"> {children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
